name: E2E - Cluster 1

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: exit 1

  build_second:
    name: build second
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Hello 2
        run: echo "hello"

  notify:
    name: notify
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs:
      - build
      - build_second
    steps:
      - name: Print
        run: echo "Printing"